# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-27 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
